### ISSUE TITLE
how to run in windows python

### ISSUE THREAD

**Issue by sc20099** [elichai/FixPrivateKey#5]
its giving errors

ex. 
```
C:\python36\Scan ETH privatekey\FixPrivateKey-master>python36 automaticfix.py ---------------------"hidden partial private key"

  File "automaticfix.py", line 21
    print privkey
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(privkey)
?

C:\python36\Scan ETH privatekey\FixPrivateKey-master>python36 automaticfix.py ---------------------"hidden partial private key"

Traceback (most recent call last):
  File "automaticfix.py", line 1, in <module>
    import FixPrivateKey
  File "C:\python36\Scan ETH privatekey\FixPrivateKey-master\FixPrivateKey.py",
line 4, in <module>
    from FixPrivateKey import (
ImportError: cannot import name 'query_yes_no'
```

**Comment by elichai** [comment]
Yeah this was written a long time ago, so it uses python 2.7

**Comment by sc20099** [comment]
Tried in python 2.7 too


C:\Prvkey\FixPrivateKey-master>python automaticfix.py 5hwC2kWaZcyzKDa
Traceback (most recent call last):
  File "automaticfix.py", line 1, in <module>
    import FixPrivateKey
  File "C:\Prvkey\FixPrivateKey-master\FixPrivateKey.py", line 3, in <module>
    from FixPrivateKey import (
ImportError: cannot import name query_yes_no

**Comment by elichai** [comment]
> ```
>   File "C:\Prvkey\FixPrivateKey-master\FixPrivateKey.py", line 3, in <module>
>     from FixPrivateKey import (

this line doesn't exist in my code here, 
I should also probably rewrite this in rust at some point, it should make it faster and maybe I'll add more heuristics
